# Copyright (c) 2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

# A GitHub workflow using CMake, Ninja and vcpkg.
# It is called "pure" because it is an example which minimizes the usage of custom GitHub actions, but leverages directly the tools that could be easily run on your development machines (i.e. CMake, vcpkg, Ninja).
name: hosted-pure-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: ${{ matrix.os }}-hosted-pure
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
    env:
      # Indicates the CMake build directory where project files and binaries are being produced.
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir/
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          path: src_repo

      - uses: actions/checkout@v4
        with:
          repository: 'microsoft/vcpkg'
          path: vcpkg
          submodules: true
          # Updated to a more recent version that should have better CLI11 support
          ref: "2024.11.16"

      # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
      - uses: lukka/get-cmake@latest
      
      # Restore both vcpkg and its artifacts from the GitHub cache service.
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v4
        with:
          # The first path is where vcpkg generates artifacts while consuming the vcpkg.json manifest file.
          # The second path is the location of vcpkg (it contains the vcpkg executable and data files).
          # The other paths starting with '!' are exclusions: they contain termporary files generated during the build of the installed packages.
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          # Updated cache key to include vcpkg version
          key: |
            ${{ hashFiles( 'src_repo/vcpkg.json' ) }}-${{ matrix.triplet }}-2024.11.16-v2
      
      - name: Show content of workspace after cache has been restored
        run: find $RUNNER_WORKSPACE
        shell: bash
      
      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: ilammy/msvc-dev-cmd@v1
      
      # Setup Ninja explicitly with a more recent version
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1
      
      # Bootstrap vcpkg if needed
      - name: Bootstrap vcpkg
        run: |
          if (!(Test-Path "${{ env.VCPKG_ROOT }}/vcpkg.exe")) {
            & "${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat"
          }
        shell: pwsh
      
      # Run CMake to generate Ninja project files, using the vcpkg's toolchain file to resolve and install the dependencies as specified in vcpkg.json.

      - name: Download ScyllaHide
        run: ./tools/setup-scylla.ps1
        shell: pwsh
        working-directory: "${{ github.workspace }}/src_repo"

      - name: Install dependencies and generate project files
        run: |
          cmake -S "${{ github.workspace }}/src_repo" -B "${{ env.CMAKE_BUILD_DIR }}" -GNinja \
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
            -DMODENGINE_DIST_SCYLLA=1 \
            -DMODENGINE_CRASH_REPORT_URL=${{ secrets.MODENGINE_CRASH_REPORT_URL }} \
            -DCPACK_GENERATOR=ZIP \
            -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/src_repo/third-party/vcpkg-overlays" \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DCMAKE_MAKE_PROGRAM="${{ env.VCPKG_ROOT }}/downloads/tools/ninja-1.12.1-windows/ninja.exe" \
            -DVCPKG_VERBOSE=ON
        shell: bash
        env:
          CC: cl
          CXX: cl

      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target package --verbose

      - name: Show content of workspace at its completion
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: 'modengine-${{ github.sha }}'
          path: '${{ env.CMAKE_BUILD_DIR }}/ModEngine-*-win64.*' # FIXME gtierney: run-cmake isn't respecting CMAKE_INSTALL_PREFIX
        if: ${{ github.event_name == 'push' }}